server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  types {
    application/manifest+json webmanifest;
  }

  location /api/ {
    proxy_pass http://api:5000/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location = /sw.js {
    add_header Cache-Control "no-cache";
    try_files $uri =404;
  }

  location = /manifest.webmanifest {
    default_type application/manifest+json;
    add_header Cache-Control "no-cache";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
